name: Daily Update and Commit

on:
  schedule:
    - cron: '0 0 */5 * *'
  workflow_dispatch:

jobs:
  update-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download file
        run: |
          mkdir -p load/m3u
          mkdir -p load/tvbox
          cd load
          wget -q https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u -O m3u/ipv6.m3u

      - name: trans
        run: |
          cd load
          python m3u2tvbox.py m3u/ipv6.m3u tvbox/ipv6.txt

      - name: merge
        run: |
          cd load
          python merge_main.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          cd load
          git diff
          git add -f .
          if ! git diff --staged --quiet; then
            git commit -m 'Daily update of load'
            git push --force
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=RELEASE_VERSION::$(date +%Y%m%d)

      - name: Create or Update Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.RELEASE_VERSION }}
          release_name: Release ${{ steps.get_version.outputs.RELEASE_VERSION }}
          draft: false
          prerelease: false
          overwrite: true

