name: Create Release on Push

on:
  push:
    branches:
      - master  # 在 master 分支有提交时触发

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Create Tag
      id: create_tag
      run: |
        TIMESTAMP=$(date +'%Y%m%d%H')
        git tag $TIMESTAMP
        git push origin $TIMESTAMP

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: Release ${{ steps.create_tag.outputs.tag }}
        body: "Automated release based on push to main branch"
        draft: false
        prerelease: false
